name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [22.x]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
            mongodb-version: latest
      - name: Build Dependencies
        run: npm install
      - name: Build Project
        run: npm run install-both
      - name: Build FE
        run: npm run build --prefix client
      - name: Build Test
        run: npm test
