name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Build Dependencies
      run: npm install
    - name: Build Project
      run: npm run install-both
    - name: Build FE
      run: npm run build --prefix client
    - name: Build BE
      run: npm start --prefix server
